name: Build App

on:
  pull_request:
    branches:
      - master
    paths:
      - '**.java'
      - '**.gradle'
      - '**.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - name: Create local.properties
        env:
          MAPS_API_KEY: ${{secrets.MAPS_API_KEY}}
        run: echo "MAPS_API_KEY=$MAPS_API_KEY" >> local.properties
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
          cache: "gradle"
        name: Setup Java JDK 11
      - name: Give gradlew Execute Permission
        run: chmod +x gradlew
      - name: Build App
        run: ./gradlew build --parallel -x test
