name: Run Tests

on:
  pull_request:
    branches:
      - master
    paths:
      - '**.java'
      - '**.gradle'
      - '**.xml'
  push:
    branches:
      - master
    paths:
      - '**.java'
      - '**.gradle'
      - '**.xml'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
          cache: "gradle"
        name: Setup Java JDK 11
      - name: Give gradlew Execute Permission
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew test
  ui-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
          cache: "gradle"
        name: Setup Java JDK 11
      - name: Give gradlew Execute Permission
        run: chmod +x gradlew
      - uses: gradle/gradle-build-action@v2
        name: Gradle Cache
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29
      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back emulated
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back emulated
          disable-animations: true
          script: ./gradlew connectedCheck
