name: Run Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
          cache: "gradle"
        name: Setup Java JDK 11
      - name: Give gradlew Execute Permission
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew test
  ui-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - name: Give gradlew Execute Permission
        run: chmod +x gradlew
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
